image: node:14

stages:
  - test
  - build

cache:
  paths:
    - build
    - .yarn
    - tsconfig.tsbuildinfo

include:
  - template: Security/SAST.gitlab-ci.yml

lint:
  stage: test
  before_script:
    - rm -rf dist
  script:
    - yarn --frozen-lockfile
    - yarn lint --format gitlab
  artifacts:
    paths:
      - gl-codequality.json
    reports:
      codequality: gl-codequality.json

audit:
  stage: test
  script:
    - npx gitlab-ci-yarn-audit-parser
  artifacts:
    reports:
      dependency_scanning: gl-dependency-scanning-report.json

sast:
  stage: test
  variables:
    SAST_EXCLUDED_ANALYZERS: bandit, brakeman, flawfinder, gosec, kubesec, phpcs-security-audit,
      pmd-apex, security-code-scan, sobelow, spotbugs
    SAST_EXCLUDED_PATHS: build, node_modules

test:
  stage: build
  needs: [ lint ]
  before_script:
    - rm -rf dist
  script:
    - yarn --frozen-lockfile
    - yarn test:coverage
  artifacts:
    reports:
      junit: test-results.xml
